CREATE DATABASE BUSINESS_DB
/* create database statement */

DROP DATABASE BUSINESS_DB
/* To delete the database*/


CREATE TABLE OWNER (
OWNER_ID INT PRIMARY KEY NOT NULL,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
JOBROLE VARCHAR (50),
SALARY DECIMAL (10,0),
ADDDRESS VARCHAR(50),
POSTCODE CHAR (10),
);
/* create table statement*/

INSERT INTO OWNER VALUES ('1','Richard','Price','CEO','100000.00','220 Easton Avenue','W1 QWR');
SELECT * FROM  OWNER
/* insert value into table*/


CREATE TABLE EMPLOYEES (
EMPLOYEE_ID INT PRIMARY KEY NOT NULL,
FIRST_NAME VARCHAR (50),
LAST_NAME  VARCHAR (50),
SALARY DECIMAL (10,0),  
);

SELECT * FROM EMPLOYEES 
INSERT INTO EMPLOYEES VALUES('1','Amy','Wells','20000.00');
INSERT INTO EMPLOYEES VALUES('2','Sandra','Harrington','18000.00');
INSERT INTO EMPLOYEES VALUES('3','Laura','Len','15000.00');
INSERT INTO EMPLOYEES VALUES('4','Tony','Tax','20000.00');
INSERT INTO EMPLOYEES VALUES('5','James','Johnson','18000.00');
INSERT INTO EMPLOYEES VALUES('6','Samantha','Smith','15000.00');


DELETE FROM EMPLOYEES                          
WHERE FIRST_NAME = 'Laura';
/* delete a record example */

SELECT DISTINCT FIRST_NAME FROM EMPLOYEES  
/* extract distinctive(unique) data from employees */  

SELECT * FROM EMPLOYEES
WHERE SALARY = '20000.00';
/* Query to show employees with specific salary of £20000.00*/ 


CREATE TABLE STAFF (
STAFF_ID INT PRIMARY KEY NOT NULL,
FIRST_NAME VARCHAR (50),
LAST_NAME VARCHAR (50),
SALARY DECIMAL (10,0),
);

SELECT * FROM STAFF
INSERT INTO STAFF VALUES ('1','John','Andrews','10000.00');
INSERT INTO STAFF VALUES ('2','Scott','Mathews','11000.00');
INSERT INTO STAFF VALUES ('3','Claire','Rivers','12000.00');


CREATE TABLE EMPLOYEE_ORIGIN (
EMPLOYEE_ORIGIN_ID INT PRIMARY KEY NOT NULL,
EMPLOYEE_FIRSTNAME VARCHAR (50),
COUNTRY VARCHAR (50),
CITY VARCHAR (50),
);

SELECT * FROM EMPLOYEE_ORIGIN 
INSERT INTO EMPLOYEE_ORIGIN VALUES ('1','Amy','England','London');
INSERT INTO EMPLOYEE_ORIGIN VALUES ('2','Sandra','China','Hong Kong');
INSERT INTO EMPLOYEE_ORIGIN VALUES ('3','Laura','France','Paris');
INSERT INTO EMPLOYEE_ORIGIN VALUES ('4','Tony','England','London');
INSERT INTO EMPLOYEE_ORIGIN VALUES ('5','James','China','Hong Kong');
INSERT INTO EMPLOYEE_ORIGIN VALUES ('6','Samantha','France','Paris');


SELECT * FROM EMPLOYEE_ORIGIN
WHERE COUNTRY ='China'
AND CITY ='Hong Kong';


SELECT * FROM EMPLOYEE_ORIGIN
WHERE CITY = 'London'
OR CITY = 'Paris';


SELECT * FROM EMPLOYEE_ORIGIN
WHERE Country = 'China'
AND (City='Hong Kong' OR City ='London');


SELECT * FROM EMPLOYEE_ORIGIN
ORDER BY COUNTRY;
/* Querying to show countries in order */


SELECT * FROM EMPLOYEE_ORIGIN
ORDER BY CITY;
/* Querying to show cities in order */


SELECT * FROM EMPLOYEE_ORIGIN
ORDER BY EMPLOYEE_FIRSTNAME;
/* Querying to show employee first name in order */


SELECT * FROM EMPLOYEE_ORIGIN
ORDER BY COUNTRY ASC
/* Ordering countries in Ascending order*/


SELECT * FROM EMPLOYEE_ORIGIN
ORDER BY COUNTRY DESC
/* Ordering countries in Descending order*/



